# Generated by Django 4.2.4 on 2023-12-21 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0002_taller_esta_lleno'),
        ('inscripcion', '0003_remove_inscripciones_id_inscripciones_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('curp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Inscripciones', to='inscripcion.inscripciones')),
                ('taller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Taller', to='taller.taller')),
            ],
        ),
    ]
