# Generated by Django 4.2.4 on 2023-12-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_asistencia_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
    ]
