# Generated by Django 4.2.4 on 2023-12-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0008_inscripciones_id_alter_inscripciones_curp'),
        ('asistencia', '0003_asistencia_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='curp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.inscripciones'),
        ),
    ]
