# Generated by Django 4.2.4 on 2023-12-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_asistencia_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='curp',
            field=models.CharField(max_length=18),
        ),
    ]
