# Generated by Django 4.2.4 on 2023-12-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_alter_asistencia_curp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='asistencia',
        ),
    ]
