# Generated by Django 4.2.4 on 2023-11-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('curp', models.CharField(default='', max_length=18)),
                ('telefono', models.TextField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=9)),
                ('correo', models.TextField()),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taller.taller')),
            ],
        ),
    ]
