# Generated by Django 4.2.4 on 2023-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_remove_inscripciones_curp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripciones',
            name='id',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='curp',
            field=models.CharField(default='', max_length=18, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
