# Generated by Django 4.2.4 on 2023-12-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_remove_inscripciones_id_inscripciones_curp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripciones',
            old_name='taller',
            new_name='id_taller',
        ),
    ]
