# Generated by Django 4.2.4 on 2023-12-21 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_taller_esta_lleno'),
        ('inscripcion', '0006_remove_inscripciones_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='taller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Inscripciones', to='taller.taller'),
        ),
    ]
