# Generated by Django 4.2.4 on 2023-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0007_inscripciones_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='curp',
            field=models.CharField(max_length=18),
        ),
    ]
