# Generated by Django 4.2.4 on 2024-01-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0008_inscripciones_id_alter_inscripciones_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='fecha_registro',
            field=models.DateField(default='2024-01-10'),
        ),
    ]
