# Generated by Django 4.2.4 on 2023-11-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('mes', models.CharField(max_length=10)),
                ('dias', models.TextField()),
                ('cupo', models.IntegerField()),
                ('instructor', models.TextField()),
                ('participantes', models.IntegerField(default=0)),
            ],
        ),
    ]
