# Generated by Django 4.2.4 on 2023-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='esta_lleno',
            field=models.BooleanField(default=False),
        ),
    ]
