# Generated by Django 4.2.4 on 2023-12-25 20:12

from django.db import migrations, models
import taller.models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_taller_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='dias',
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha',
            field=models.TextField(default=taller.models.default_dates),
        ),
    ]
