# Generated by Django 4.2.4 on 2023-12-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_remove_taller_dias_taller_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
