# Generated by Django 4.2.4 on 2023-11-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_rename_telefono_empleado_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='edad',
        ),
    ]
