# Generated by Django 4.2.4 on 2023-11-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_remove_empleado_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
    ]
