# Generated by Django 4.2.4 on 2023-12-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_remove_empleado_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='usuario',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
